# Site settings
title:          stephen
description:    "organized chaos"
baseurl:        "/"
url:            "https://swoicik.github.io/"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

# Author
author:
  name:         swoicik
  url:          https://swoicik.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year/:title
permalink:      /:categories/:title/
paginate:       10
